In [1]:
import numpy as np

a = np.arange(1,7).reshape(2,3)
print(a)

# そのまま足せる
print(a + 1)

# 自乗も出来る
print(a**2)

print(np.log(a))

# 全要素の合計
print(np.sum(a))

# 全要素の平均
print(np.average(a))

[[1 2 3]
 [4 5 6]]
[[2 3 4]
 [5 6 7]]
[[ 1  4  9]
 [16 25 36]]
[[ 0.          0.69314718  1.09861229]
 [ 1.38629436  1.60943791  1.79175947]]
21
3.5


In [2]:
#列毎の和
print(np.sum(a, axis=0))

#行毎の和
print(np.sum(a, axis=1))

[5 7 9]
[ 6 15]


In [3]:
a = np.arange(6).reshape(2,3)
b = np.arange(6, 12).reshape(2,3)
print(a)
print(b)
# 足し算
print(a + b)

# 引き算
print(a - b)

# 掛け算
print(a * b)

# 割り算
print(a / b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]
[[ 6  8 10]
 [12 14 16]]
[[-6 -6 -6]
 [-6 -6 -6]]
[[ 0  7 16]
 [27 40 55]]
[[ 0.          0.14285714  0.25      ]
 [ 0.33333333  0.4         0.45454545]]


In [4]:
a = np.arange(4)
b = np.arange(4, 8)
print(a)
print(b)

# 行列の掛け算
print(a.dot(b))

a= np.arange(6).reshape(2,3)
b= np.arange(6).reshape(3,2)
print(a)
print(b)

# 行列の掛け算
print(a.dot(b))

[0 1 2 3]
[4 5 6 7]
38
[[0 1 2]
 [3 4 5]]
[[0 1]
 [2 3]
 [4 5]]
[[10 13]
 [28 40]]


In [5]:
a = np.array([[0,6,3], [-2, 7, 2],[0,0,3]])
print(a)
# 転置行列
print(a.T)

# 行列式 0でないので逆行列がある
print(np.linalg.det(a))

# 逆行列
print(np.linalg.inv(a))


# 固有値、　固有ベクトル
la, v = np.linalg.eig(a)
print(la)
print(v)

[[ 0  6  3]
 [-2  7  2]
 [ 0  0  3]]
[[ 0 -2  0]
 [ 6  7  0]
 [ 3  2  3]]
36.0
[[ 0.58333333 -0.5        -0.25      ]
 [ 0.16666667  0.         -0.16666667]
 [ 0.          0.          0.33333333]]
[ 3.  4.  3.]
[[-0.89442719 -0.83205029  0.43643578]
 [-0.4472136  -0.5547002  -0.21821789]
 [ 0.          0.          0.87287156]]
